apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-cart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: retail-store
  source: 
    repoURL: https://github.com/lhussain-usefulbi/argo-cd-2.git
    targetRevision: gitops
    path: argocd-app/src/cart/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://44304FD5FF4B8A13705BDC46611FDA23.gr7.ap-south-1.eks.amazonaws.com
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
