apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  # RBAC policy definitions in CSV format
  policy.csv: |
    # Developers can get applications in 'myproject'
    p, role:developer, applications, *, *, deny
    # Developers can sync applications in 'myproject'
    p, role:developer, applications, sync, myproject/*, allow 
    # Admins can perform any action on any application
    p, role:admin, applications, *, *, allow
    # Assign 'developer' role to user 'alice'
    g, hussain, role:developer
    # Assign 'admin' role to user 'bob'
    g, bob, role:admin 
  # Default role for users not explicitly assigned
  policy.default: role:readonly
